package com.softwaretree.jdxandroidautoincrementexample.model;

import java.util.Date;

public class Employee {
    private int id;
    private String name;
    private Date DOB;  
    private boolean exempt; 
    private float compensation;
       
    /**
     * Default no-arg constructor needed for JDX
     */
    public Employee() {
    }

    // id field is generated by the database.
    public Employee(String name, Date DOB, boolean exempt, float compensation) {
        this.name = name;
        this.DOB = DOB;
        this.exempt = exempt;
        this.compensation = compensation;
    }
    
    public int getId() {
        return id;
    }
    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }

    public Date getDOB() {
        return DOB;
    }
    public void setDOB(Date DOB) {
        this.DOB = DOB;
    }

    public boolean getExempt() {
        return exempt;
    }
    public void setExempt(boolean exempt) {
        this.exempt = exempt;
    }

    public float getCompensation() {
        return compensation;
    }
    public void setCompensation(float compensation) {
        this.compensation = compensation;
    }
    
    
}
